#Equipment
@baseUrl = http://localhost:3001
###

# LISTA TODOS OS EQUIPAMENTOS
###
GET {{baseUrl}}/equipment/

# LISTA APENAS UM EQUIPAMENTO
###
GET {{baseUrl}}/equipment/1

# CRIA UM EQUIPAMENTO
###
POST {{baseUrl}}/equipment/
Content-Type: application/json

{
 "model": "BC-HORTFRUTS",
 "serialNumber": "558799442",
 "status": "Maintenance",
 "installationDate": "2025-04-05T14:48:00.000Z",
 "lastMaintenance": "2025-04-05T14:48:00.000Z",
 "storeId": "59834826-3748-4c29-964a-6c99217cb5cb"
}

# REMOVE UM EQUIPAMENTO
###
DELETE {{baseUrl}}/equipment/2

# ATUALIZA UM EQUIPAMENT
###
PATCH {{baseUrl}}/equipment/2
Content-Type: : application/json

{
  
}